### ISSUE TITLE
1000 request/sec example

### ISSUE THREAD

**Issue by Altiano** [eriklupander/gotling#16]
Hey Erik,
Just want to ask,
Ho do I simulate like 1000 rps initiated (not complete),
and with the `yml` file,
how do I setup something like 200 unique users in that 1000 requests?

**Comment by eriklupander** [comment]
Hi!

If it were possible to sleep for 200 milliseconds, I think one could run a simulation with 200 users that does 5 requests with a 200 ms sleep in between. E.g (psuedo-yaml):

```
---
iterations: 10
users: 200
rampup: 20
actions:
  - http: # request 1
  - sleep: 200ms
  - http: # request 2
  - sleep: 200ms
  - http: # request 3
  - sleep: 200ms
  - http: # request 4
  - sleep: 200ms
  - http: # request 5
  - sleep: 200ms
```

However, Gotling does not currently support sleeps other that in whole seconds, but that should be easy to add. Let me see if I can fix that in a few days.
