### ISSUE TITLE
evaluate and use fasthttp

### ISSUE THREAD

**Issue by missedone** [eriklupander/gotling#6]
i saw this https://github.com/rakyll/boom/issues/94, we probably can evaluate it and use it if it really promise.

**Comment by eriklupander** [comment]
Sounds great. Assigned the issue to you if you want to give it a shot.

HTTP performance have been quite good so far, on my laptop (OS X) I usually run out of file handles before the CPU usage goes above 100% on a single core. But having less CPU usage due to HTTP implementation overhead sounds good.

Regarding memory use, I've seen pretty consistent behaviour where Gotling uses about 8 kb (each goroutine) x number of concurrent "users".

**Comment by missedone** [comment]
sure, will have a try later

**Comment by missedone** [comment]
i just pushed the initial implementation with fasthttp on `feature/fasthttp` branch.
for now, only GET is supported, i did a quick test, and found that there is performance degradation with fasthttp compared to stdlib net/http.
will dig deeper later to understand why.

below is an example, you can uncomment the `client: fasthttp` line to use fasthttp, by default it's using net/http:
```yaml
---
iterations: 10
users: 10
rampup: 10
actions:
  - http:
      title: Ping Google
      method: GET
      # client: fasthttp
      url: https://www.google.com
```
