### ISSUE TITLE
Add support for file-based templates

### ISSUE THREAD

**Issue by eriklupander** [eriklupander/gotling#7]
Instead of inlining POST bodies etc, add support for reading those as templates from files. Example syntax:

```
- http:
      method: POST
      url: http://localhost:9183/mypostablepath
      template: myproject/somepostbody.json
```

Where myproject is a folder in $GOTLING_HOME/templates 

A sample template file could be like this, e.g. uses same ${paramName} syntax:

**somepostbody.json**
`{"name":"${fullName}}", "age":"${age}"}`

For the templates, it would be interesting to adapt StringTemplate syntax and capabilities, but that can be evaluated in the future.
