### ISSUE TITLE
Host request-header Support

### ISSUE THREAD

**Issue by wahmedswl** [eriklupander/gotling#9]
Hi, is Host http header is supported. I want to stress test linkerd service which works with Host http header.

Any help would be appreciated, thanks

**Comment by retgits** [comment]
If you're still interested in this, it is now supported. You can add HTTP headers to HTTP requests in the YAML file:

```yaml
- http:
    title: Some title
    method: POST
    headers:
        foo: bar
        hello: world
        host: myhost.service.com
``` 

Good luck 🙌
